/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 airforce.gltf --transform 
Files: airforce.gltf [220.94MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoes\airforce1\airforce-transformed.glb [5.72MB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/airforce-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.146]}>
        <mesh geometry={nodes.Plane044.geometry} material={materials['Insole Material']} />
        <mesh geometry={nodes.Plane044_1.geometry} material={materials['Main Body Material']} />
        <mesh geometry={nodes.Plane044_2.geometry} material={materials['Sole Material']} />
        <mesh geometry={nodes.Plane044_3.geometry} material={materials['Main Shoe Inside']} />
      </group>
      <mesh geometry={nodes.Nike_Air_Force_Right.geometry} material={materials['Insole Material right']} position={[0, 0, -0.136]} />
      <mesh geometry={nodes.Laces006.geometry} material={materials['Laces Material']} position={[-0.087, 0.081, 0.144]} rotation={[0, 0, 0.45]} />
      <mesh geometry={nodes.Nike_Logo_left005.geometry} material={materials['Logo left Material']} position={[0.213, 0.065, 0.179]} rotation={[0, 0.174, 0]} />
      <mesh geometry={nodes.Nike_Logo_right005.geometry} material={materials['Logo right Material']} position={[0.213, 0.065, 0.059]} rotation={[0, 0.044, 0]} />
      <mesh geometry={nodes.Shoe_Flap010.geometry} material={materials['Flap Material.002']} position={[0, -0.005, 0.146]} />
      <mesh geometry={nodes.Shoe_Flap011.geometry} material={materials['Tag material']} position={[0, -0.005, 0.146]} />
      <mesh geometry={nodes.Shoe_Flap008.geometry} material={materials['Tag materialright.001']} position={[0, -0.005, -0.136]} />
    </group>
  )
}

useGLTF.preload('/airforce-transformed.glb')
