/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 airmax.gltf --transform 
Files: airmax.gltf [7.7MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoes\airmax\airmax-transformed.glb [441.9KB] (94%)
Author: mercurio22 (https://sketchfab.com/mercurio22)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-90-premium-4b2280c16b67481cba0fe7ffacd77011
Title: Nike Air Max 90 Premium
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/airmax-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base1_Base2_0.geometry} material={materials.Base2} scale={0.021} />
      <mesh geometry={nodes.Base1_Logo_0.geometry} material={materials.Logo} scale={0.021} />
      <mesh geometry={nodes.Base1_lambert1_0.geometry} material={materials.lambert1} scale={0.021} />
      <mesh geometry={nodes.Base1_Cordones_0.geometry} material={materials.Cordones} scale={0.021} />
      <mesh geometry={nodes.Base1_Suela_0.geometry} material={materials.Suela} scale={0.021} />
    </group>
  )
}

useGLTF.preload('/airmax-transformed.glb')
