/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Shoe10.gltf --transform 
Files: Shoe10.gltf [26.64MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoes\shoe10\Shoe10-transformed.glb [394.62KB] (99%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Shoe10-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.supreme_x_Nike_Air_More_Uptempo1.geometry} material={materials.supreme_x_Nike_Air_More_UptempoSG} />
    </group>
  )
}

useGLTF.preload('/Shoe10-transformed.glb')
