/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe4.gltf --transform 
Files: shoe4.gltf [34.52MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoe4\shoe4-transformed.glb [9.46MB] (73%)
Author: ryanbair (https://sketchfab.com/ryanbair)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-dunk-high-hawaii-b91992960af540c7a1edef97bf4d7ef1
Title: Nike Dunk High Hawaii
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.tex_u1_v1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/shoe4-transformed.glb')
