/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe6.gltf --transform 
Files: shoe6.gltf [27.89MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoe6\shoe6-transformed.glb [770.39KB] (97%)
Author: FletchTech (https://sketchfab.com/FletchTech)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-react-presto-running-shoes-c9b878b60d524413becd63dae298b027
Title: NIKE REACT PRESTO RUNNING SHOES
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe6-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/shoe6-transformed.glb')
