/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe9.gltf --transform 
Files: shoe9.gltf [5.22MB] > D:\Babadon\WEBD\ThreeJS\Nike-Let's Do It!\shoes\shoe9\shoe9-transformed.glb [154.26KB] (97%)
Author: Thomson 🚀 (https://sketchfab.com/thomson159)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-90-ce4a4e5847b34cd6b4ed0ecf134f556d
Title: Nike Air Max 90
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.Texture} />
    </group>
  )
}

useGLTF.preload('/shoe9-transformed.glb')
